"""Add Queue model

Revision ID: 7738a96de7c1
Revises: 
Create Date: 2026-09-18 16:50:23.977943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7738a96de7c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('called_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_consultation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'IN_CONSULTATION', 'COMPLETED', 'NO_SHOW', 'CANCELLED', name='queuestatus'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_queues_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_queues_created_by_users')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_queues_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_queues_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_queues_appointment_id')),
    sa.UniqueConstraint('doctor_id', 'queue_number', name='uq_queues_doctor_number')
    )
    op.create_index('ix_queues_appointment_id', 'queues', ['appointment_id'], unique=False)
    op.create_index('ix_queues_doctor_id', 'queues', ['doctor_id'], unique=False)
    op.create_index('ix_queues_status', 'queues', ['status'], unique=False)
    op.drop_column('patients', 'marital_status')
    op.drop_column('patients', 'family_medical_history')
    op.drop_column('patients', 'ethnicity')
    op.drop_column('patients', 'medical_history')
    op.drop_column('patients', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('occupation', sa.VARCHAR(length=100), nullable=True))
    op.add_column('patients', sa.Column('medical_history', sa.TEXT(), nullable=True))
    op.add_column('patients', sa.Column('ethnicity', sa.VARCHAR(length=50), nullable=True))
    op.add_column('patients', sa.Column('family_medical_history', sa.TEXT(), nullable=True))
    op.add_column('patients', sa.Column('marital_status', sa.VARCHAR(length=50), nullable=True))
    op.drop_index('ix_queues_status', table_name='queues')
    op.drop_index('ix_queues_doctor_id', table_name='queues')
    op.drop_index('ix_queues_appointment_id', table_name='queues')
    op.drop_table('queues')
    # ### end Alembic commands ###
